defaults:
  - _self_
  - env: ???
  - solver: ???
  - evaluator: ???

train_dir: null
eval_dir: logs/evals/${now:%Y.%m.%d}/${now:%H%M%S} # where to save evaluation results
env_log_dir: ${eval_dir} # where the gym env can save logs
# Other config componenents can reference this top-level verbosity parameter
# Use 0 for minimal printing, 1 for info, 2 debugging
verbosity: 0
eager: true # tensorflow execution mode

# See:
# https://github.com/facebookresearch/hydra/issues/910
# https://github.com/facebookresearch/hydra/issues/1651
hydra:
  run:
    dir: ${eval_dir}
  output_subdir: hydra_cfg
