defaults:
  - sb3_base@sb3_sac

sb3_sac:
  policy_cls:
    _target_: hydra.utils.get_class
    path: stable_baselines3.sac.MlpPolicy
  agent_cls:
    _target_: hydra.utils.get_class
    path: stable_baselines3.SAC
  agent_kwargs:
    batch_size: 64
    learning_starts: 100
    learning_rate: 0.0003
    gamma: 0.97
    tau: 0.005
    train_freq: 1
    n_layers: 3
    neurons_per_layer: 256
    ent_coef: 'auto_0.1'
