defaults:
  - sb3_base@sb3_mhsac

sb3_mhsac:
  policy_cls:
    _target_: hydra.utils.get_class
    path: saic5g.solvers.multi_heads.mhsac.ResidualMultiHeadSACPolicy
  agent_cls:
    _target_: hydra.utils.get_class
    path: saic5g.solvers.multi_heads.mhsac.MultiHeadSAC
  agent_kwargs:
    policy_kwargs:
      features_extractor_class: 
        _target_: hydra.utils.get_class
        path: saic5g.solvers.sb3_policy_networks.batchnorm_feature_extractor.BatchNormFeaturesExtractor
      activation_fn: 
        _target_: hydra.utils.get_class
        path: torch.nn.ReLU
      features_extractor_kwargs:
        net_arch: [128,64,16]
        normalize: False
      net_arch:
        qf: [256,256,256]
        pi: [256,256,256]
    learning_rate: 0.0003
    learning_starts: 100
    batch_size: 64
    train_freq: 1
    gamma: 0.97
    tau: 0.005
    ent_coef: auto_0.1
